### ISSUE TITLE
unable to see any packets related to open5gs+UERANSIM 

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#178]
@aligungr i have sucessfully connected my open5gs with  UERANSIM but unable to see any authenication or UE connect update in wireshark plzz help

**Comment by aligungr** [comment]
@mimo123-code I also have no time to analysis this problem. But here's my guesses.
Make sure
- running wireshark with sudo
- you have latest version of wireshark
- listening "any" interface on wireshark
- selecting correct filter on wireshark

If you are still unable to see NAS/NGAP packets, please be more attentive because these packets must be certainly there :)
