### ISSUE TITLE
How to use TUN interface for GTP-U

### ISSUE THREAD

**Issue by s5uishida** [aligungr/UERANSIM#179]
Hi @aligungr 

Thank you very much for supporting U-Plane. It's great!

By the way, I want to communicate using the TUN interface, and even though I select `4) pdu-session-establishment`, I could not find the TUN interface on the UERANSIM side.

I would be very glad if you could tell me how to use it.

Thank you very much in advance.

**Comment by aligungr** [comment]
Hi @s5uishida

I will provide more information in wiki page later, but for now I want to inform you and the community briefly.

We are going to transform UERANSIM to an ecosystem with multiple features and tools included. For example what you normally run will be called flow testing. We will also provide TUN interface and many other tools in order to utilize UE's internet connectivity.
But for now, TUN interface feature is not complete. But in flow testing, after successful establishment of PDU Sessions, UE automatically sends ping request according to testing.yaml file. (Without need of TUN interface.)

Soon we will provide many features such as TUN interface, UE-Box and custom web browser etc. to our ecosystem.

---

By the way I wonder if you successfully ping google.com after pdu session management? Related log message should be visible on default terminal or global.log file.

**Comment by s5uishida** [comment]
Hi @aligungr 

I think the concept of the ecosystem is excellent.

In addition to verifying the functions of 5GC, I would like to use the TUN interface for research to improve the performance of U-Plane.

Also, it seems that I was able to ping `google.com` with the combination of latest Open5GS and UERANSIM.

`global.log`
```
[2020-11-13 13:50:34.689] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] NGSetup procedure is successful
[2020-11-13 13:50:37.731] [INFO] [SYSTEM] Waiting for user-defined sleep (15 s)
[2020-11-13 13:50:38.040] [SUCCESS] [PROCEDURE_RESULT] [ue-imsi-901700000000003] Registration is successful
[2020-11-13 13:50:51.904] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] PDU Session Establishment is successful
[2020-11-13 13:50:51.908] [SUCCESS] [PROCEDURE_RESULT] [ue-imsi-901700000000003] PDU Session Establishment is successful
[2020-11-13 13:50:52.993] [SUCCESS] [UE_APP] [ue-imsi-901700000000003] Ping reply from google.com (172.217.161.238) in 217 ms
```

Thank you very much!

**Comment by acetcom** [comment]
@aligungr It's fantastic! I'd appreciated UERANSIM supporting for Open5GS.
@s5uishida Could you share pcap? Thank you so much for you effort.

**Comment by s5uishida** [comment]
Hi @acetcom 

The log and pcap files are attached below.

- Open5GS (5GC) - `192.168.0.111/24 (if=enp0s8)`
- UERANSIM (5G SA UE/RAN) - `192.168.0.112/24 (if=enp0s8)`

The changes in the UERANSIM configuration files are as follows.

`UERANSIM/config/open5gs/gnb.yaml`
```
--- gnb.yaml.orig       2020-11-13 16:27:26.480112999 +0000
+++ gnb.yaml    2020-11-13 13:45:23.471257985 +0000
@@ -2,7 +2,7 @@
 tac: 1
 nci: '000000000000000000000000000000010000'
 
-host: 127.0.0.1
+host: 192.168.0.112
 gtpPort: 2152
 tunPort: 49972
 
@@ -20,7 +20,7 @@
         hex: '5580'
       amfPointer:
         hex: 'a8'
-    host: 127.0.0.5
+    host: 192.168.0.111
     port: 38412
 
 supportedTAs:
@@ -37,4 +37,4 @@
               value:
                 hex: '010203'
 
-ignoreStreamIds: true
\ No newline at end of file
+ignoreStreamIds: true
```

The execution result is as shown in the following log.

`global.log`
```
[2020-11-13 16:32:52.925] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] NGSetup procedure is successful
[2020-11-13 16:32:55.755] [INFO] [SYSTEM] Waiting for user-defined sleep (15 s)
[2020-11-13 16:32:56.207] [SUCCESS] [PROCEDURE_RESULT] [ue-imsi-901700000000003] Registration is successful
[2020-11-13 16:33:09.942] [SUCCESS] [PROCEDURE_RESULT] [ue-imsi-901700000000003] PDU Session Establishment is successful
[2020-11-13 16:33:09.957] [SUCCESS] [PROCEDURE_RESULT] [gnb-1] PDU Session Establishment is successful
[2020-11-13 16:33:10.826] [SUCCESS] [UE_APP] [ue-imsi-901700000000003] Ping reply from google.com (172.217.161.206) in 28 ms
```
- [ueransim_logs.tar.gz](https://github.com/aligungr/UERANSIM/files/5538183/ueransim_logs.tar.gz)
- [open5gs_ueransim.pcap.gz](https://github.com/aligungr/UERANSIM/files/5538186/open5gs_ueransim.pcap.gz)
- [open5gs_logs.tar.gz](https://github.com/aligungr/UERANSIM/files/5538187/open5gs_logs.tar.gz)

**Comment by acetcom** [comment]
@s5uishida and @aligungr 

Thanks for sharing the pcap. So I reviewed it. Everything seems to be fine except for one thing.

![Screenshot from 2020-11-13 13-00-24](https://user-images.githubusercontent.com/4222492/99105270-38105b80-25b0-11eb-936b-ee210157ea76.png)

In the picture above, other commercial UEs send Extended Protocol Configuration Option. If ePCO is implemented in UERANSIM, every packet looks perfect. For your reference, I've attached the pcap containing ePCO. It is at packet number 111.
[open5gs.pcapng.gz](https://github.com/aligungr/UERANSIM/files/5538559/open5gs.pcapng.gz)

And, If you find any problem in Open5GS packet, please do not hesitate to let me know.
Since I am watching and looking at this repository, I can see it right away if you post the issues here.

Thank you so much!
Sukchan

**Comment by aligungr** [comment]
@s5uishida and @acetcom
Thank you very much for your contributions and sharings.

PCO is not implemented yet in UERANSIM. I almost forgot the PCO, thanks for reminding and it will be implemented soon.

**Comment by mimo123-code** [comment]
hello @s5uishida  i am getting these error unable to ping google.[UE_APP] [ue-imsi-901700000000003] Ping timeout for google.com (142.250.67.46) after 3 sec no response. plzz help

**Comment by aligungr** [comment]
@acetcom Protocol configuration options is now included in PDU session establishment request. UE requests IP allocation with NAS signalling and DNS information for IPv4. (In general IPv6 is not implemented yet).

@mimo123-code Please make sure that you have successfully configured core network side and review core network documentation (Open5GS, free5gc etc.), especially IP routing and forwarding part.

**Comment by aligungr** [comment]
TUN interface is now read, see #186 .
