### ISSUE TITLE
rrc setup request

### ISSUE THREAD

**Issue by mimo123-code** [aligungr/UERANSIM#204]
hello @aligungr  i am unable to see rrc setup request which is given by UE to gnb during initial 5G registration. is rrc procedure not implemented in UERANSIM

**Comment by aligungr** [comment]
Hello @mimo123-code NR radio interface including RRC protocol is under development, and not complete yet.

Also we internally use RRC, but wireshark cannot see them at the moment.

**Comment by mimo123-code** [comment]
ok thanks @aligungr . i just want to ask one question and sorry for bothering you. i want to perform registration reject or tau reject between my gnb and UE everytime i want to connect . can you tell me in which file i have to to change the code.it will be a great help

**Comment by aligungr** [comment]
@mimo123-code

Unfortunately I cannot help to you because of the time constraints.

I think firstly you should have deeper understanding of how 5G system works.

I'm attaching some quick links for you.

[3GPP TS 23.501](https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/15.02.00_60/ts_123501v150200p.pdf)
[3GPP TS 23.502](https://www.etsi.org/deliver/etsi_ts/123500_123599/123502/15.02.00_60/ts_123502v150200p.pdf)
[3GPP TS 24.501](https://www.etsi.org/deliver/etsi_ts/124500_124599/124501/15.03.00_60/ts_124501v150300p.pdf)

Please check 'registration reject' for example, in 24.501.
Many other information related to registration can be found in these specs.

**Comment by mimo123-code** [comment]
ok thanks a lot @aligungr
