### ISSUE TITLE
UE-AMBR

### ISSUE THREAD

**Issue by DendoD96** [aligungr/UERANSIM#205]
Hello @aligungr, is UE-AMBR implemented? I have seen that the value received from the AMF is stored in the UE context, but then it is not used.
Thank you

**Comment by aligungr** [comment]
Hello @DendoD96. Yes we store this value, but currently gNB does not evaluate it. This feature is on roadmap, but not complete yet.

**Comment by DendoD96** [comment]
@aligungr Thank you, do you plan to use leaky bucket or something like that?

**Comment by aligungr** [comment]
@DendoD96 Yes we plan to use leaky bucket algorithm (meter variant) to control bandwidth.

**Comment by DendoD96** [comment]
@aligungr Ok, to do some tests to be included in my thesis I have implemented a naive version of the token bucket (which should be leaky bucket meter variant) In the next few weeks I could improve it and open a pull request if you are interested.

**Comment by aligungr** [comment]
@DendoD96 Sure, I would be glad if you implement this and open a pull request.

**Comment by DendoD96** [comment]
@aligungr Nice, i will try to do it!

**Comment by DendoD96** [comment]
Hi @aligungr, i have a few questions before start implementing.

Reading [3GPP TS 23.501](https://www.etsi.org/deliver/etsi_ts/123500_123599/123501/16.06.00_60/ts_123501v160600p.pdf) (paragraph 5.7.2.6) it says that each RAN shall set UE_AMBR=min(sum(APN_AMBR), UE_AMBR). In GtpTask, the GtpContext does not contains the UE_AMBR. Can I enter this information in the context or would you prefer to proceed in another way?

Furtermore, GtpTask handles IwUplinkData and IwGtpDownlink with an event loop. Using a blocking token bucket to restrict one direction would also restrict the other.  In your opinion, would it be better to use an unblocked token bucket (for example through the use of promises) or to divide uplink and downlink management?

**Comment by aligungr** [comment]
Hi @DendoD96.

For the first question,

Normally UE AMBR is stored in `NgapUeContext`, and since each layer has independent contexts, `GtpContext` should also store this value by own.

We have `PduSessionTree` in `GtpContext` and `PduSessionResource` in `PduSessionTree`. Therefore we should store the AMBR value in `PduSessionResource` in order to use in GTP layer. So, please feel free to add this field to `PduSessionResource`.

Also since `PduSessionResource` is created by NGAP layer, and pushed to GTP layer, you can assign AMBR value in `NgapPduSessionManagement` line ~50, just like we assign `resource.ueId` and `resource.pduSessionId` etc. (`resource.ambr = associatedUe.aggregateMaximumBitRate` etc.)

After that GTP layer can utilize the AMBR value inside of the `PduSessionResource`.

---

I'm not really sure if I understand the second question correctly, but:

GtpTask handling of IwUplinkData and IwGtpDownlink are very lightweight operations. In our `NtsTask` architecture, event loops almost always perform lightweight operations in GtpTask, NgapTask etc. Therefore we should not use blocking codes in the event loops. And also premises and java like multi threading/concurrency are also not desired. Instead we use `pushDelayed` for example, to schedule a code block to execute after delay, or if we need another thread we can create another `NtsTask`.

Nevertheless, as far as I know we should just drop the packets if user reaches the bandwidth limit. Instead of for example delaying and delivering the packet later. If just dropping is sufficient, then I think tocken bucket algorithm will be lightweight also. Otherwise I think we should use 2 separate thread/task to control uplink and downlink as you questioned.

But I as said it depends on the limitation method. Should we just drop the packets or deliver lately? I'm not sure which one would be better. I'm sure that you know this concept better than me, so I'm open to your opinions.

By the way, I'm reopening the issue, and we can use here for further discussion if it is needed.

**Comment by DendoD96** [comment]
Hi @aligungr, thank you for this fast reply. As far as i know, packets could be treated in different ways. For example: they could be simply dropped or they could be delayed for a later transmission. These different solutions could be implemented with a strategy pattern, but the later transmission could be a bit tricky.

**Comment by aligungr** [comment]
I think we should go for packet dropping first, instead of delayed transmission. And later the other strategy may enrich gNBs capabilities.

**Comment by DendoD96** [comment]
Yes, i agree with you.
