### ISSUE TITLE
Problem with nr-binder

### ISSUE THREAD

**Issue by pragnyakiri** [aligungr/UERANSIM#255]
Hello,

On the "Usage" page (UERANSIM Wiki page), under section "Using the TUN via ./nr-binder", it is written that this command  "./nr-binder 10.45.0.2 curl google.com"  will use UE's internet connection with IP 10.45.0.2.

I have two questions:

1. What is the IP address 10.45.0.2, is it any random IP Address on the internet ?
2. On running this command, I receive a reply in the form of http content on the terminal. But I don't receive a single packet on the wireshark. I open wireshark and configure it to catch packets from 'uesimtun0' interface, which is the ue interface. So even though a packes are exchanged when this command is run, there are no packets captured in wireshark running at the uesimtun0 interface. Does that mean, the packets are not using the uesimtun0 interface ?

I have configured free5gc, nr-gnb and nr-ue properly, and a PDU session is successfully established without any error.

Thanks,
Pradnya

**Comment by aligungr** [comment]
@pragnyakiri 

Good questions.

1. It's the IP address of the PDU session you just established successfully. Each PDU session has a dynamically assigned IP address in 5G system. You can see your IP address using `nr-cli` command or you can read from UE logs. For free5gc default IP is something like 60.60.0.X, for open5gs it is 10.45.0.X.
2. You should give the exact same IP to the `nr-binder` to use `uesimtunX` interfaces. Otherwise default external interface is used which is not desired of course. For example if your PDU session IP is 60.60.0.9, then run `nr-binder 60.60.0.9` etc. In this way you can see the traffic is occurred in `uesimtunX` interface.

**Comment by pragnyakiri** [comment]
Thank you for the detailed explanation.
I corrected the IP address and it worked.
Could you add the description of the IP address on the Wiki page (Usage) so that it is clear to all users ?

Thanks,
Pradnya

**Comment by aligungr** [comment]
Sure, thanks for the suggestion.
