### ISSUE TITLE
RRC messages dont show in wireshark

### ISSUE THREAD

**Issue by iman432** [aligungr/UERANSIM#275]
Hi,
Thanks for your great job,i have a issue with RRC messages in wireshark and they are showing as
![image](https://user-images.githubusercontent.com/44318450/112589077-1ce70f80-8e1e-11eb-97f1-871ddae78cbb.jpg)
 UDP on port 4997 , RRC is enabled in wireshark protocols but still they are as UDP.there is any other configuration for seeing correctly?(latest version of UERANSIM and Wireshark version is 3.4.4)

**Comment by aligungr** [comment]
Actually these UDP datagrams contains **RLS** packets. RLS protocol is designed by UERANSIM, and it means Radio Link Simulation. (Main impl. is available at https://github.com/aligungr/UERANSIM/tree/master/src/urs/rls)

RLS PDU may contain one of the followings:
1. RLS control messages
2. IPv4 data packets
3. RRC messages

For **RRC** messages, RLS PDU format is the following:

`[RLS MESSAGE] := [RLS HEADER] [RRC MESSAGE]`

Therefore we need to remove RLS header (first few bytes at the beginning) in order to decode RRC message.

That's why wireshark cannot decode RRC messages. Perhaps we should write a custom dissector or a plugin for wireshark in order to decode RRC messages.

**Comment by p3ngdump** [comment]
Oh.. I see the UERANSIM packet structure. Thank you

How can I extract the RRC message?
It has constant pattern? we have to make the custom extractor??

Thank you!!

**Comment by aligungr** [comment]
RLS PDU contains a variable-length header. Of course it has a very well-defined structure, but its structure changes according to the content.

Please see these code snippet with 34 lines, in the function named `Decode`:
https://github.com/aligungr/UERANSIM/blob/8cceeae618082abda98f2218458c8f1b7b78438c/src/urs/rls/rls.cpp#L14

This is the actual code that decodes the RLS header. The payload field corresponds to the RRC packet, (if the message type is `RLS_PAYLOAD_TRANSPORT` and the payload type is `RRC`)

But still a custom dissector is required for wireshark to decode this. Perhaps I might write one in the future.

**Comment by p3ngdump** [comment]
Oh! I know..
I will use the Decode function.

Thank for your reply.

**Comment by kajtmzb** [comment]
> But still a custom dissector is required for wireshark to decode this. Perhaps I might write one in the future.

 Hi Ali, that would be greatly appreciated!

**Comment by p3ngdump** [comment]
Good morning. I was using a decoder based on the decode function you uploaded above. In recent versions, the field values seem to be slightly different. Are there any related decode codes?

Thank for your effort.

@aligungr

**Comment by aligungr** [comment]
Good morning @p3ngdump Yes, RLS PDU structure slightly changed in the latest 3.1.7 version. See `src/urs/rls_pdu.hpp` and `src/urs/rls_pdu.cpp`

**Comment by p3ngdump** [comment]
I see! Thank  you! @aligungr

**Comment by louisroyer** [comment]
Hello, I created a [wireshark dissector](https://github.com/louisroyer/RLS-wireshark-dissector) for rls 3.1.7. Not sure about right RRC dissectors to call for each channel (for `DL_DCCH` and `UL_DCCH` when using `rrc.dl.dcch` and `rrc.ul.dcch` packets were malformed, so I used `rrc.bcch.fach` and `rrc.bcch.bch2` but I'm not sure this is correct). Can someone confirm that `payload` in case of `PDU_DELIVERY` message contains the channel id?
Also, I could not found what `sti` means in rls header.

**Comment by p3ngdump** [comment]
@louisroyer It's very good ..!! In my thought, maybe `sti` is UE's token or gNodeB's token value

The rrc area use `wireshark rrc dissector`? or define yourself?

**Comment by louisroyer** [comment]
@p3ngdump Ok, if it is a token then it doesn't matter. I now use [wireshark’s `lte_rrc` dissector](https://gitlab.com/wireshark/wireshark/-/wikis/LTE-RRC).

**Comment by aligungr** [comment]
@louisroyer 

I checked you dissector and it seems very nice and works like a charm, thank you very much for this plugin.

---

> Can someone confirm that payload in case of PDU_DELIVERY message with RRC contains the channel id; and with DATA an identifier of the session used?

Yes, exactly like what you said.

---

> I could not found what sti means in rls header

STI is the RLS Temporary Identifier, and it's pretty much the same thing like @p3ngdump said. Every time UE or gNB node starts, it generates a unique temporary identifier.

---

I think there is only one thing we need to solve:

RRC in 4G and 5G are entirely different protocols. Therefore we should use `nr-rrc` instead of `lte_rrc` in the dissector. For example, currently when UE sends a `RRCSetupRequest`, Wireshark incorrectly decodes it as `RRCConnectionReestablishmentRequest`. Because RRC protocol and message structures changed so much in LTE and 5G.

I'd be glad if we can solve this. And after that, this plugin will be very useful for me and for the community.

I appreciate your work.
Thanks

**Comment by louisroyer** [comment]
Thanks for your feedback. I now use `nr-rrc` and this solved every decoding issues I had.

**Comment by aligungr** [comment]
@louisroyer That's great, I'll check this tonight

**Comment by p3ngdump** [comment]
@louisroyer I check your wireshark tool. It's so great! Thanks for your work
![image](https://user-images.githubusercontent.com/25604847/116523255-00ecf700-a911-11eb-8a22-607e9c63a3bf.png)

**Comment by aligungr** [comment]
Thanks so much @louisroyer 

I checked the plugin and it's works like a charm.
I'm putting a link to the UERANSIM Wiki page to your repository.


By the way I'd be glad, if you we can put your plugin to the main UERANSIM repository. (For example in `tools` folder) In this way we can update the plugin in a single commit whenever RLS version changes as well.

If you want to include it in the main UERANSIM repositry, please make a PR request with the code (with your copyrights)
(Otherwise it's still OK to provide the plugin in a separate repository, no worries.)


Thanks again for this awesome dissector

Ali

**Comment by louisroyer** [comment]
Of course, it is even better in the main repository. See PR #308.

**Comment by iman432** [comment]
Thank you all for great job.
