### ISSUE TITLE
Does nr-binder have port connection limit?

### ISSUE THREAD

**Issue by lee850220** [aligungr/UERANSIM#322]
I am using iperf to test UE connection, but when I use iperf's "dualtest" or iperf3's "bidir", it caused connection refused when server try to connect to client (UE).

In iperf:
Client side
![image](https://user-images.githubusercontent.com/18142489/119123764-7e181180-ba62-11eb-9052-b3c00c224af6.png)

Server side
![image](https://user-images.githubusercontent.com/18142489/119123839-95ef9580-ba62-11eb-9cfe-c97e3ec5c957.png)

In iperf3:
Client side
![image](https://user-images.githubusercontent.com/18142489/119124278-11514700-ba63-11eb-9786-bdd8a6ccf44d.png)

Server side
![image](https://user-images.githubusercontent.com/18142489/119124345-21692680-ba63-11eb-8e72-c70cf3f35c9a.png)

But it can test bidirection individually.
In iperf3:
Client side
![image](https://user-images.githubusercontent.com/18142489/119125409-532ebd00-ba64-11eb-99bb-190462a1f1df.png)

Server side
![image](https://user-images.githubusercontent.com/18142489/119125346-414d1a00-ba64-11eb-8d3c-efc27d6b2796.png)

**Comment by lee850220** [comment]
Update:
Another test in iperf3 bidir
Client side:
![image](https://user-images.githubusercontent.com/18142489/119127197-9722c180-ba66-11eb-9fda-a32b7d3bf3bd.png)

Server side:
![image](https://user-images.githubusercontent.com/18142489/119127356-cfc29b00-ba66-11eb-8ddd-6d3e48da616d.png)

**Comment by aligungr** [comment]
@lee850220 

I think `nr-binder` should not limit anything. Actually `nr-binder` is a really simple tool and the only thing it does is binding applications to `uesimtunX` interface instead of the machine's default interface such as `enp8s0` etc.

I don't know much about iperf, but I think `nr-binder` may not be suitable for its usage case. Because `nr-binder` relies on IP routing configurations.

My suggestion is to use `B, --bind host` option in iperf, instead of using `nr-binder`

For example instead of:

```bash
./nr-binder 60.60.0.1 "iperf ......"
```

You can directly use

```bash
iperf -B 60.60.0.1 ......
```

Please try this and check if it's working. If still it does not work, then try to start UEs with `nr-ue --no-route-config` parameter. I think it should work in either case.

**Comment by lee850220** [comment]
@aligungr 
I found that this is routing problem, thanks for your reply.
