### ISSUE TITLE
Regarding thoughts on using golang 

### ISSUE THREAD

**Issue by manoj1919** [aligungr/UERANSIM#330]
Hi Ali,
I have been following and using your UERANSIM for educating myself about the 5G RAN. As I am new to the programming world, I felt C++ is somewhat intimidating to learn. Do you think we can use golang to achieve the same results. The reason I am asking the question is, I want to make a golang version of UERANSIM, to take my understanding of the RAN to the next level. Do you think it's a good idea? is it doable at all? Any thoughts are welcome.

Thank you! and appreciate your work on UERANSIM,

Manoj

**Comment by aligungr** [comment]
Hi Manoj

In theory you can use any programming language to solve any computational problem as long as the language itself is Turing-complete. Therefore it is possible to implement UERANSIM in golang. But in practice it's very unlikely to meet some requirements such as performance, maintainability and code quality.

Golang is primarily designed for cloud-native applications and web developments. If you ask for a 5G core network for example, I would definitely say you should go for the golang. But for 5G RAN and UE implementation you need a more low-level (close to silicon) programming language such as C++.

My humble suggestion for your specific case is the following: Making a golang version of UERANSIM will not much improve your programming and 5G knowledge. Because both the language C++ and the logic behind the implementation are really complex. Instead you can begin with some basic projects and try to improve your skills day by day. 

I wish you all the best, and may real success be with you

Ali

**Comment by anhtrung87vn** [comment]
Hi @aligungr,

I am learning gNB programming by reading your source code and your project is a really good reference for me.
I am a fresher, so I don't know if there is a software design for your project, if yes, could you share it? It will help me a lot when trying to understand the code flow.

Thank you so much.
Trung.

**Comment by aligungr** [comment]
Hi @anhtrung87vn 

I'm glad to hear about it and I wish you all the best.

Currently I'm not able to point a reference, but I'm planning to write a paper in the future about design and implementation of UERANSIM.

I hope I can find sufficient time and publish the document.

Regards

**Comment by anhtrung87vn** [comment]
Thank @aligungr

**Comment by manoj1919** [comment]
Thanks @aligungr . I am closing this issue :)
