### ISSUE TITLE
Name Resolution Fails when Pinging

### ISSUE THREAD

**Issue by karim140995** [aligungr/UERANSIM#482]
Hello,
Im trying to create a 5G test bed. I configured two virtual box UBUNTU 20.04 LTS VM'S to set up a 5G network, below the configuration I have:

VM 1 with Open5GsCore has an interface to the NAT network and internal network interface.
VM 2 with UERANSIM has only an internal network interface.
I followed this [tutorial](https://nickvsnetworking.com/my-first-5g-core-open5gs-and-ueransim/) in order to configure open5Gscore and UERANSIM, everything worked like charm, a PDU Session is successfully set and a tunnel is created when i run nr-ue. the only problem I have is that I cant ping google.com -I uesimtun0. I can however do it on ip addresses. I tried everything including disabling systemd-resolver.
Note that i added the following rules in order to route from VM 2 to VM 1:
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
sudo systemctl stop ufw

**Comment by lcph** [comment]
I am also experiencing the same issue. Can only ping ip adresses but not a url.
Probably a dns problem...but haven't figured out to fix this problem yet.

**Comment by aligungr** [comment]
@karim140995 @lcph 

Indeed it's normal behavior. Because the ping utility performs the DNS query before the ping. Therefore ping tool always use the standard DNS mechanism regardless of whether you bind to the uesimtunX, or any other interface. That is, DNS resolution is independent of the network interface.

And, UERANSIM cannot alter the working mechanism of Linux `ping` tool. Thus, this won't work.

Best regards

**Comment by karim140995** [comment]
@lcph @aligungr 
Adding sudo ip r add default dev uesimtun0 to the UERANSIM machine fixed the problem.
