### ISSUE TITLE
Traffic generated from outside the UERANSIM's host keeps getting stucked at the UE

### ISSUE THREAD

**Issue by MaFe1401** [aligungr/UERANSIM#581]
Is this scenario feasible? 

![scenario](https://user-images.githubusercontent.com/57569408/202861385-57a2d695-4258-4b54-bccf-737bdf0ea9e0.png)

I can ping from uesimtun0 to 192.168.3.3, but pings from 192.168.2.3 to 192.168.3.3 get stuck at uesimtun0, as well as pings from 192.168.3.3 to 192.168.2.3 get stuck at ogstun. Why?

**Comment by infinitydon** [comment]
Not sure if this works since the uesimtun0 is a /32 IP, you can try to add a route on the UERANSIM: **_ip route add 192.168.3.0/24 via 10.45.0.1_**

On PC listener set route: **_ip route 192.168.2.0/24 via 192.168.3.2_**

Am assuming you are assuming a /24, update according to your subnet

Also you must use **192.168.2.2** as the gateway on PC Talker for the PC Listener IP network (am assuming you are already doing this)

**Comment by MaFe1401** [comment]
Hi @infinitydon thanks for the answer!

Sadly, I already tried that. This is the routing table in the UERANSIM Virtual Machine:
![imagen](https://user-images.githubusercontent.com/57569408/202866224-d3a0920e-a869-45b2-901f-030307b60602.png)

This is the routing table in the listener PC: 
![imagen](https://user-images.githubusercontent.com/57569408/202866341-8cc74004-941f-4958-b4ee-da7a2c308473.png)

And the routing table in the talker PC:
![imagen](https://user-images.githubusercontent.com/57569408/202866430-b3577881-cf41-440a-936f-d2ea8989cb56.png)

**Comment by infinitydon** [comment]
I suspected that it might not work, issue will likely be on the uesimtun0 implementation..

The other thing I tried is to use an overlay like GRE (i.e. between UERANSIM **_uesimtun0_** and UPF **_ogstun_**) and then do the normal routing at each hop respectively (I also disabled the masquerading on the UPF i.e. I did not use **_iptables -t nat -A POSTROUTING -s 10.45.0.0/16 ! -o ogstun -j MASQUERADE_**)

Might not be a performant solution but might be worth trying though.

**Comment by myonlystarWang** [comment]
I think there may be two problems here：
1. How to send the ping packety from the talker to open5gs or listener. I think it would be solved with routing rule settings.
2. Open5gs should correctly send the ping packet from talker to the listener.But as far as I know,traffics like previously mentioned be considered as spoofing traffic,so that open5gs will drop these packets.

**Comment by MaFe1401** [comment]
> 2\. Open5gs should correctly send the ping packet from talker to the listener.But as far as I know,traffics like previously mentioned be considered as spoofing traffic,so that open5gs will drop these packets.

@myonlystarWang I think this is exactly what is happening. Now that you say it I can see this error at the UPF:

![imagen](https://user-images.githubusercontent.com/57569408/202897523-53d8a1d2-d367-444a-be3a-c756d2e83580.png)

Does it have any solution?

**Comment by MaFe1401** [comment]
> @myonlystarWang I think this is exactly what is happening. Now that you say it I can see this error at the UPF:
> 
> ![imagen](https://user-images.githubusercontent.com/57569408/202897523-53d8a1d2-d367-444a-be3a-c756d2e83580.png)

Ok so by commenting the code snippet that made this error appear, the ping request is now able to reach 192.168.3.3 from 192.168.2.3, but the reply gets stucked at ogstun (10.45.0.1). However, if I ping from 192.168.3.3 to 10.45.0.2 (uesimtun0), it works. Could it be a problem related to routing, or is it possible that UERANSIM is doing something similar to what the UPF did?

**Comment by myonlystarWang** [comment]
> > @myonlystarWang I think this is exactly what is happening. Now that you say it I can see this error at the UPF:
> > ![imagen](https://user-images.githubusercontent.com/57569408/202897523-53d8a1d2-d367-444a-be3a-c756d2e83580.png)
> 
> Ok so by commenting the code snippet that made this error appear, the ping request is now able to reach 192.168.3.3 from 192.168.2.3, but the reply gets stucked at ogstun (10.45.0.1). However, if I ping from 192.168.3.3 to 10.45.0.2 (uesimtun0), it works. Could it be a problem related to routing, or is it possible that UERANSIM is doing something similar to what the UPF did?

from 192.168.2.3 to 192.168.3.3, we call it uplink
form 192.168.3.3 to 192.168.2.3 we call it downlink
The uplink traffic can arrive the listener because of the Open5gs do not check source address after your comment.
But the downlink traffic will be discarded because of the destination address will still be checked
This is actually one of the main functions of the core network, UE address check, which only provide services for terminals with assigned addresses from Open5gs
In fact, I also encountered such problems and initiated a issue in the community[https://github.com/open5gs/open5gs/issues/1826](url)

**Comment by MaFe1401** [comment]
Considering what you said, I have solved it by masquerading the talker PC, at the UERANSIM VM: 

```
sudo iptables -t nat -A POSTROUTING -o uesimtun0 -j MASQUERADE
```
In this way, the source IP address is changed from 192.168.2.3 to 10.45.0.2 when packets leave uesimtun0, so UPF won't discard uplink traffic coming from talker PC (since it thinks traffic is created at uesimtun0) and also won't discard downlink traffic because it thinks traffic is directed to uesimtun0.
So no changes are needed in the code (I deleted the comments I did before).

**Comment by myonlystarWang** [comment]
> Considering what you said, I have solved it by masquerading the talker PC, at the UERANSIM VM:
> 
> ```
> sudo iptables -t nat -A POSTROUTING -o uesimtun0 -j MASQUERADE
> ```
> 
> In this way, the source IP address is changed from 192.168.2.3 to 10.45.0.2 when packets leave uesimtun0, so UPF won't discard uplink traffic coming from talker PC (since it thinks traffic is created at uesimtun0) and also won't discard downlink traffic because it thinks traffic is directed to uesimtun0. So no changes are needed in the code (I deleted the comments I did before).

Yes, talker can do business normally by using NAT like you mentioned.
But if you want the listener communicate the talker first,the problem still exist.
